/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(register)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(register)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/booking` | `/booking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authentication)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authentication)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(register)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(register)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/booking` | `/booking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(authentication)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(authentication)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(register)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(register)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(sign-in)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(sign-in)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/booking${`?${string}` | `#${string}` | ''}` | `/booking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(register)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(register)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(sign-in)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/booking` | `/booking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
